// Tarjetas de bebé: la palabra en español y en inglés, y de qué dibujo sale.
// Las usa el juego de tarjetas del aparato; el servidor genera el dibujo (1 bpp,
// 320x320, listo para la pantalla) y la voz (Piper, ADPCM), y los dos viajan en
// el paquete de contenido (ver assets.ts). El aparato NO decodifica PNG ni MP3.
//
// Los dibujos salen de Lucide (lucide-static, licencia ISC), que se baja de
// jsDelivr y se rasteriza con sharp (la misma librería que ya convierte las
// fotos): no hace falta Python ni rsvg-convert en la imagen.
//
// Por qué no hay categoría de COLORES: la pantalla es de tinta y las tarjetas
// van en 1 bpp (blanco y negro), así que un dibujo no puede decir "rojo" ni
// "azul". En su lugar va "formas", que es lo que sí se entiende en blanco y
// negro y es una categoría clásica de tarjetas para bebés.
//
// `icon`:
//   "<nombre>"  → el SVG de Lucide con ese nombre
//   "num:<n>"   → dibujo generado acá: n puntos para contar (Lucide no trae dígitos)

export type CardCategory =
  | "animales" | "comida" | "casa" | "cuerpo" | "formas"
  | "numeros" | "vehiculos" | "naturaleza" | "ropa" | "juguetes";

export type Card = { id: string; cat: CardCategory; es: string; en: string; icon: string };

export const CARDS: Card[] = [
  // ── animales ──
  { id: "ani-perro",                 cat: "animales",    es: "perro",                 en: "dog",               icon: "dog" },
  { id: "ani-gato",                  cat: "animales",    es: "gato",                  en: "cat",               icon: "cat" },
  { id: "ani-pajaro",                cat: "animales",    es: "pájaro",                en: "bird",              icon: "bird" },
  { id: "ani-pez",                   cat: "animales",    es: "pez",                   en: "fish",              icon: "fish" },
  { id: "ani-conejo",                cat: "animales",    es: "conejo",                en: "rabbit",            icon: "rabbit" },
  { id: "ani-tortuga",               cat: "animales",    es: "tortuga",               en: "turtle",            icon: "turtle" },
  { id: "ani-caracol",               cat: "animales",    es: "caracol",               en: "snail",             icon: "snail" },
  { id: "ani-ardilla",               cat: "animales",    es: "ardilla",               en: "squirrel",          icon: "squirrel" },
  { id: "ani-raton",                 cat: "animales",    es: "ratón",                 en: "mouse",             icon: "rat" },
  { id: "ani-gusano",                cat: "animales",    es: "gusano",                en: "worm",              icon: "worm" },
  { id: "ani-insecto",               cat: "animales",    es: "insecto",               en: "bug",               icon: "bug" },
  { id: "ani-panda",                 cat: "animales",    es: "panda",                 en: "panda",             icon: "panda" },
  { id: "ani-camaron",               cat: "animales",    es: "camarón",               en: "shrimp",            icon: "shrimp" },
  { id: "ani-huevo",                 cat: "animales",    es: "huevo",                 en: "egg",               icon: "egg" },
  { id: "ani-pluma",                 cat: "animales",    es: "pluma",                 en: "feather",           icon: "feather" },
  { id: "ani-huella",                cat: "animales",    es: "huella",                en: "paw print",         icon: "paw-print" },
  { id: "ani-hueso",                 cat: "animales",    es: "hueso",                 en: "bone",              icon: "bone" },
  { id: "ani-caracola",              cat: "animales",    es: "caracola",              en: "seashell",          icon: "shell" },
  { id: "ani-pollito",               cat: "animales",    es: "pollito",               en: "chick",             icon: "bird" },
  { id: "ani-caballito-de-mar",      cat: "animales",    es: "caballito de mar",      en: "seahorse",          icon: "fish-symbol" },
  { id: "ani-nido",                  cat: "animales",    es: "nido",                  en: "birdhouse",         icon: "birdhouse" },
  // ── comida ──
  { id: "com-manzana",               cat: "comida",      es: "manzana",               en: "apple",             icon: "apple" },
  { id: "com-banana",                cat: "comida",      es: "banana",                en: "banana",            icon: "banana" },
  { id: "com-zanahoria",             cat: "comida",      es: "zanahoria",             en: "carrot",            icon: "carrot" },
  { id: "com-cereza",                cat: "comida",      es: "cereza",                en: "cherry",            icon: "cherry" },
  { id: "com-uva",                   cat: "comida",      es: "uva",                   en: "grapes",            icon: "grape" },
  { id: "com-naranja",               cat: "comida",      es: "naranja",               en: "orange",            icon: "citrus" },
  { id: "com-leche",                 cat: "comida",      es: "leche",                 en: "milk",              icon: "milk" },
  { id: "com-pizza",                 cat: "comida",      es: "pizza",                 en: "pizza",             icon: "pizza" },
  { id: "com-sandwich",              cat: "comida",      es: "sándwich",              en: "sandwich",          icon: "sandwich" },
  { id: "com-helado",                cat: "comida",      es: "helado",                en: "ice cream",         icon: "ice-cream-cone" },
  { id: "com-copa-de-helado",        cat: "comida",      es: "copa de helado",        en: "ice cream bowl",    icon: "ice-cream-bowl" },
  { id: "com-medialuna",             cat: "comida",      es: "medialuna",             en: "croissant",         icon: "croissant" },
  { id: "com-galleta",               cat: "comida",      es: "galleta",               en: "cookie",            icon: "cookie" },
  { id: "com-palomitas",             cat: "comida",      es: "palomitas",             en: "popcorn",           icon: "popcorn" },
  { id: "com-ensalada",              cat: "comida",      es: "ensalada",              en: "salad",             icon: "salad" },
  { id: "com-sopa",                  cat: "comida",      es: "sopa",                  en: "soup",              icon: "soup" },
  { id: "com-carne",                 cat: "comida",      es: "carne",                 en: "meat",              icon: "beef" },
  { id: "com-jamon",                 cat: "comida",      es: "jamón",                 en: "ham",               icon: "ham" },
  { id: "com-trigo",                 cat: "comida",      es: "trigo",                 en: "wheat",             icon: "wheat" },
  { id: "com-nuez",                  cat: "comida",      es: "nuez",                  en: "nut",               icon: "nut" },
  { id: "com-poroto",                cat: "comida",      es: "poroto",                en: "bean",              icon: "bean" },
  { id: "com-caramelo",              cat: "comida",      es: "caramelo",              en: "candy",             icon: "candy" },
  { id: "com-torta",                 cat: "comida",      es: "torta",                 en: "cake",              icon: "cake" },
  { id: "com-porcion-de-torta",      cat: "comida",      es: "porción de torta",      en: "cake slice",        icon: "cake-slice" },
  { id: "com-dona",                  cat: "comida",      es: "dona",                  en: "donut",             icon: "donut" },
  { id: "com-cafe",                  cat: "comida",      es: "café",                  en: "coffee",            icon: "coffee" },
  { id: "com-gaseosa",               cat: "comida",      es: "gaseosa",               en: "soda",              icon: "cup-soda" },
  { id: "com-hamburguesa",           cat: "comida",      es: "hamburguesa",           en: "hamburger",         icon: "hamburger" },
  { id: "com-huevo-frito",           cat: "comida",      es: "huevo frito",           en: "fried egg",         icon: "egg-fried" },
  { id: "com-cubiertos",             cat: "comida",      es: "cubiertos",             en: "cutlery",           icon: "utensils" },
  { id: "com-gorro-de-cocinero",     cat: "comida",      es: "gorro de cocinero",     en: "chef hat",          icon: "chef-hat" },
  { id: "com-olla",                  cat: "comida",      es: "olla",                  en: "pot",               icon: "cooking-pot" },
  { id: "com-pata-de-pollo",         cat: "comida",      es: "pata de pollo",         en: "drumstick",         icon: "drumstick" },
  { id: "com-verdura",               cat: "comida",      es: "verdura",               en: "greens",            icon: "leafy-green" },
  { id: "com-baston-de-caramelo",    cat: "comida",      es: "bastón de caramelo",    en: "candy cane",        icon: "candy-cane" },
  { id: "com-miel",                  cat: "comida",      es: "miel",                  en: "honeycomb",         icon: "hexagon" },
  // ── casa ──
  { id: "cas-casa",                  cat: "casa",        es: "casa",                  en: "house",             icon: "house" },
  { id: "cas-cama",                  cat: "casa",        es: "cama",                  en: "bed",               icon: "bed" },
  { id: "cas-lampara",               cat: "casa",        es: "lámpara",               en: "lamp",              icon: "lamp" },
  { id: "cas-puerta",                cat: "casa",        es: "puerta",                en: "door",              icon: "door-open" },
  { id: "cas-sillon",                cat: "casa",        es: "sillón",                en: "sofa",              icon: "sofa" },
  { id: "cas-silla",                 cat: "casa",        es: "silla",                 en: "armchair",          icon: "armchair" },
  { id: "cas-heladera",              cat: "casa",        es: "heladera",              en: "fridge",            icon: "refrigerator" },
  { id: "cas-microondas",            cat: "casa",        es: "microondas",            en: "microwave",         icon: "microwave" },
  { id: "cas-lavarropas",            cat: "casa",        es: "lavarropas",            en: "washing machine",   icon: "washing-machine" },
  { id: "cas-banera",                cat: "casa",        es: "bañera",                en: "bathtub",           icon: "bath" },
  { id: "cas-inodoro",               cat: "casa",        es: "inodoro",               en: "toilet",            icon: "toilet" },
  { id: "cas-ducha",                 cat: "casa",        es: "ducha",                 en: "shower",            icon: "shower-head" },
  { id: "cas-llave",                 cat: "casa",        es: "llave",                 en: "key",               icon: "key" },
  { id: "cas-reloj",                 cat: "casa",        es: "reloj",                 en: "clock",             icon: "clock" },
  { id: "cas-libro",                 cat: "casa",        es: "libro",                 en: "book",              icon: "book" },
  { id: "cas-persiana",              cat: "casa",        es: "persiana",              en: "blinds",            icon: "blinds" },
  { id: "cas-martillo",              cat: "casa",        es: "martillo",              en: "hammer",            icon: "hammer" },
  { id: "cas-llave-inglesa",         cat: "casa",        es: "llave inglesa",         en: "wrench",            icon: "wrench" },
  { id: "cas-tijera",                cat: "casa",        es: "tijera",                en: "scissors",          icon: "scissors" },
  { id: "cas-pincel",                cat: "casa",        es: "pincel",                en: "paintbrush",        icon: "paintbrush" },
  { id: "cas-lapiz",                 cat: "casa",        es: "lápiz",                 en: "pencil",            icon: "pencil" },
  { id: "cas-paleta",                cat: "casa",        es: "paleta",                en: "palette",           icon: "palette" },
  { id: "cas-escoba",                cat: "casa",        es: "escoba",                en: "broom",             icon: "broom" },
  { id: "cas-basura",                cat: "casa",        es: "basura",                en: "trash",             icon: "trash" },
  { id: "cas-lamparita",             cat: "casa",        es: "lamparita",             en: "light bulb",        icon: "lightbulb" },
  { id: "cas-enchufe",               cat: "casa",        es: "enchufe",               en: "plug",              icon: "plug" },
  { id: "cas-pila",                  cat: "casa",        es: "pila",                  en: "battery",           icon: "battery" },
  { id: "cas-ventilador",            cat: "casa",        es: "ventilador",            en: "fan",               icon: "fan" },
  { id: "cas-escalera",              cat: "casa",        es: "escalera",              en: "stairs",            icon: "door-stairwell" },
  { id: "cas-espejo",                cat: "casa",        es: "espejo",                en: "frame",             icon: "frame" },
  { id: "cas-mecedora",              cat: "casa",        es: "mecedora",              en: "rocking chair",     icon: "rocking-chair" },
  { id: "cas-despertador",           cat: "casa",        es: "despertador",           en: "alarm clock",       icon: "alarm-clock" },
  { id: "cas-telefono",              cat: "casa",        es: "teléfono",              en: "phone",             icon: "phone" },
  { id: "cas-televisor",             cat: "casa",        es: "televisor",             en: "television",        icon: "tv" },
  // ── cuerpo ──
  { id: "cue-mano",                  cat: "cuerpo",      es: "mano",                  en: "hand",              icon: "hand" },
  { id: "cue-pie",                   cat: "cuerpo",      es: "pie",                   en: "footprints",        icon: "footprints" },
  { id: "cue-ojo",                   cat: "cuerpo",      es: "ojo",                   en: "eye",               icon: "eye" },
  { id: "cue-oreja",                 cat: "cuerpo",      es: "oreja",                 en: "ear",               icon: "ear" },
  { id: "cue-cerebro",               cat: "cuerpo",      es: "cerebro",               en: "brain",             icon: "brain" },
  { id: "cue-corazon",               cat: "cuerpo",      es: "corazón",               en: "heart",             icon: "heart" },
  { id: "cue-bebe",                  cat: "cuerpo",      es: "bebé",                  en: "baby",              icon: "baby" },
  { id: "cue-persona",               cat: "cuerpo",      es: "persona",               en: "person",            icon: "person-standing" },
  { id: "cue-gente",                 cat: "cuerpo",      es: "gente",                 en: "people",            icon: "users" },
  { id: "cue-anteojos",              cat: "cuerpo",      es: "anteojos",              en: "glasses",           icon: "glasses" },
  { id: "cue-apreton-de-manos",      cat: "cuerpo",      es: "apretón de manos",      en: "handshake",         icon: "handshake" },
  { id: "cue-puno",                  cat: "cuerpo",      es: "puño",                  en: "fist",              icon: "hand-fist" },
  { id: "cue-mano-con-corazon",      cat: "cuerpo",      es: "mano con corazón",      en: "caring hand",       icon: "hand-heart" },
  { id: "cue-craneo",                cat: "cuerpo",      es: "cráneo",                en: "skull",             icon: "skull" },
  { id: "cue-termometro",            cat: "cuerpo",      es: "termómetro",            en: "thermometer",       icon: "thermometer" },
  { id: "cue-curita",                cat: "cuerpo",      es: "curita",                en: "bandage",           icon: "bandage" },
  { id: "cue-pastilla",              cat: "cuerpo",      es: "pastilla",              en: "pill",              icon: "pill" },
  { id: "cue-estetoscopio",          cat: "cuerpo",      es: "estetoscopio",          en: "stethoscope",       icon: "stethoscope" },
  // ── formas ──
  { id: "for-circulo",               cat: "formas",      es: "círculo",               en: "circle",            icon: "circle" },
  { id: "for-cuadrado",              cat: "formas",      es: "cuadrado",              en: "square",            icon: "squircle" },
  { id: "for-triangulo",             cat: "formas",      es: "triángulo",             en: "triangle",          icon: "triangle" },
  { id: "for-estrella",              cat: "formas",      es: "estrella",              en: "star",              icon: "star" },
  { id: "for-corazon",               cat: "formas",      es: "corazón",               en: "heart",             icon: "heart" },
  { id: "for-rombo",                 cat: "formas",      es: "rombo",                 en: "diamond",           icon: "diamond" },
  { id: "for-hexagono",              cat: "formas",      es: "hexágono",              en: "hexagon",           icon: "hexagon" },
  { id: "for-octogono",              cat: "formas",      es: "octógono",              en: "octagon",           icon: "octagon" },
  { id: "for-pentagono",             cat: "formas",      es: "pentágono",             en: "pentagon",          icon: "pentagon" },
  { id: "for-rectangulo",            cat: "formas",      es: "rectángulo",            en: "rectangle",         icon: "rectangle-horizontal" },
  { id: "for-cono",                  cat: "formas",      es: "cono",                  en: "cone",              icon: "cone" },
  { id: "for-cilindro",              cat: "formas",      es: "cilindro",              en: "cylinder",          icon: "cylinder" },
  { id: "for-cubo",                  cat: "formas",      es: "cubo",                  en: "cube",              icon: "cuboid" },
  { id: "for-piramide",              cat: "formas",      es: "pirámide",              en: "pyramid",           icon: "pyramid" },
  { id: "for-formas",                cat: "formas",      es: "formas",                en: "shapes",            icon: "shapes" },
  // ── numeros ──
  { id: "num-uno",                   cat: "numeros",     es: "uno",                   en: "one",               icon: "num:1" },
  { id: "num-dos",                   cat: "numeros",     es: "dos",                   en: "two",               icon: "num:2" },
  { id: "num-tres",                  cat: "numeros",     es: "tres",                  en: "three",             icon: "num:3" },
  { id: "num-cuatro",                cat: "numeros",     es: "cuatro",                en: "four",              icon: "num:4" },
  { id: "num-cinco",                 cat: "numeros",     es: "cinco",                 en: "five",              icon: "num:5" },
  { id: "num-seis",                  cat: "numeros",     es: "seis",                  en: "six",               icon: "num:6" },
  { id: "num-siete",                 cat: "numeros",     es: "siete",                 en: "seven",             icon: "num:7" },
  { id: "num-ocho",                  cat: "numeros",     es: "ocho",                  en: "eight",             icon: "num:8" },
  { id: "num-nueve",                 cat: "numeros",     es: "nueve",                 en: "nine",              icon: "num:9" },
  { id: "num-diez",                  cat: "numeros",     es: "diez",                  en: "ten",               icon: "num:10" },
  // ── vehiculos ──
  { id: "veh-auto",                  cat: "vehiculos",   es: "auto",                  en: "car",               icon: "car" },
  { id: "veh-colectivo",             cat: "vehiculos",   es: "colectivo",             en: "bus",               icon: "bus" },
  { id: "veh-camion",                cat: "vehiculos",   es: "camión",                en: "truck",             icon: "truck" },
  { id: "veh-bicicleta",             cat: "vehiculos",   es: "bicicleta",             en: "bicycle",           icon: "bike" },
  { id: "veh-moto",                  cat: "vehiculos",   es: "moto",                  en: "motorbike",         icon: "motorbike" },
  { id: "veh-avion",                 cat: "vehiculos",   es: "avión",                 en: "airplane",          icon: "plane" },
  { id: "veh-tren",                  cat: "vehiculos",   es: "tren",                  en: "train",             icon: "train-front" },
  { id: "veh-barco",                 cat: "vehiculos",   es: "barco",                 en: "ship",              icon: "ship" },
  { id: "veh-cohete",                cat: "vehiculos",   es: "cohete",                en: "rocket",            icon: "rocket" },
  { id: "veh-tractor",               cat: "vehiculos",   es: "tractor",               en: "tractor",           icon: "tractor" },
  { id: "veh-ambulancia",            cat: "vehiculos",   es: "ambulancia",            en: "ambulance",         icon: "ambulance" },
  { id: "veh-velero",                cat: "vehiculos",   es: "velero",                en: "sailboat",          icon: "sailboat" },
  { id: "veh-casa-rodante",          cat: "vehiculos",   es: "casa rodante",          en: "caravan",           icon: "caravan" },
  { id: "veh-autoelevador",          cat: "vehiculos",   es: "autoelevador",          en: "forklift",          icon: "forklift" },
  { id: "veh-tranvia",               cat: "vehiculos",   es: "tranvía",               en: "tram",              icon: "tram-front" },
  { id: "veh-taxi",                  cat: "vehiculos",   es: "taxi",                  en: "taxi",              icon: "car-taxi-front" },
  { id: "veh-teleferico",            cat: "vehiculos",   es: "teleférico",            en: "cable car",         icon: "cable-car" },
  { id: "veh-ancla",                 cat: "vehiculos",   es: "ancla",                 en: "anchor",            icon: "anchor" },
  { id: "veh-surtidor",              cat: "vehiculos",   es: "surtidor",              en: "fuel pump",         icon: "fuel" },
  { id: "veh-cono-de-transito",      cat: "vehiculos",   es: "cono de tránsito",      en: "traffic cone",      icon: "traffic-cone" },
  { id: "veh-semaforo",              cat: "vehiculos",   es: "semáforo",              en: "parking meter",     icon: "parking-meter" },
  { id: "veh-despegue",              cat: "vehiculos",   es: "despegue",              en: "take off",          icon: "plane-takeoff" },
  { id: "veh-aterrizaje",            cat: "vehiculos",   es: "aterrizaje",            en: "landing",           icon: "plane-landing" },
  { id: "veh-vias",                  cat: "vehiculos",   es: "vías",                  en: "train track",       icon: "train-track" },
  { id: "veh-timon",                 cat: "vehiculos",   es: "timón",                 en: "ship wheel",        icon: "ship-wheel" },
  { id: "veh-patineta",              cat: "vehiculos",   es: "patineta",              en: "scooter",           icon: "scooter" },
  // ── naturaleza ──
  { id: "nat-sol",                   cat: "naturaleza",  es: "sol",                   en: "sun",               icon: "sun" },
  { id: "nat-luna",                  cat: "naturaleza",  es: "luna",                  en: "moon",              icon: "moon" },
  { id: "nat-nube",                  cat: "naturaleza",  es: "nube",                  en: "cloud",             icon: "cloud" },
  { id: "nat-lluvia",                cat: "naturaleza",  es: "lluvia",                en: "rain",              icon: "cloud-rain" },
  { id: "nat-nevada",                cat: "naturaleza",  es: "nevada",                en: "snowfall",          icon: "cloud-snow" },
  { id: "nat-copo-de-nieve",         cat: "naturaleza",  es: "copo de nieve",         en: "snowflake",         icon: "snowflake" },
  { id: "nat-arcoiris",              cat: "naturaleza",  es: "arcoíris",              en: "rainbow",           icon: "rainbow" },
  { id: "nat-pino",                  cat: "naturaleza",  es: "pino",                  en: "pine tree",         icon: "tree-pine" },
  { id: "nat-arbol",                 cat: "naturaleza",  es: "árbol",                 en: "tree",              icon: "tree-deciduous" },
  { id: "nat-palmera",               cat: "naturaleza",  es: "palmera",               en: "palm tree",         icon: "tree-palm" },
  { id: "nat-bosque",                cat: "naturaleza",  es: "bosque",                en: "forest",            icon: "trees" },
  { id: "nat-flor",                  cat: "naturaleza",  es: "flor",                  en: "flower",            icon: "flower" },
  { id: "nat-hoja",                  cat: "naturaleza",  es: "hoja",                  en: "leaf",              icon: "leaf" },
  { id: "nat-brote",                 cat: "naturaleza",  es: "brote",                 en: "sprout",            icon: "sprout" },
  { id: "nat-montana",               cat: "naturaleza",  es: "montaña",               en: "mountain",          icon: "mountain" },
  { id: "nat-olas",                  cat: "naturaleza",  es: "olas",                  en: "waves",             icon: "waves-horizontal" },
  { id: "nat-gota",                  cat: "naturaleza",  es: "gota",                  en: "drop",              icon: "droplet" },
  { id: "nat-fuego",                 cat: "naturaleza",  es: "fuego",                 en: "fire",              icon: "flame" },
  { id: "nat-viento",                cat: "naturaleza",  es: "viento",                en: "wind",              icon: "wind" },
  { id: "nat-tornado",               cat: "naturaleza",  es: "tornado",               en: "tornado",           icon: "tornado" },
  { id: "nat-amanecer",              cat: "naturaleza",  es: "amanecer",              en: "sunrise",           icon: "sunrise" },
  { id: "nat-atardecer",             cat: "naturaleza",  es: "atardecer",             en: "sunset",            icon: "sunset" },
  { id: "nat-rayo",                  cat: "naturaleza",  es: "rayo",                  en: "lightning",         icon: "cloud-lightning" },
  { id: "nat-tierra",                cat: "naturaleza",  es: "tierra",                en: "earth",             icon: "earth" },
  { id: "nat-trebol",                cat: "naturaleza",  es: "trébol",                en: "clover",            icon: "clover" },
  { id: "nat-carpa",                 cat: "naturaleza",  es: "carpa",                 en: "tent",              icon: "tent" },
  { id: "nat-nieve-en-la-montana",   cat: "naturaleza",  es: "nieve en la montaña",   en: "snowy mountain",    icon: "mountain-snow" },
  { id: "nat-paraguas",              cat: "naturaleza",  es: "paraguas",              en: "umbrella",          icon: "umbrella" },
  { id: "nat-estrella-y-luna",       cat: "naturaleza",  es: "estrella y luna",       en: "moon and star",     icon: "moon-star" },
  // ── ropa ──
  { id: "rop-remera",                cat: "ropa",        es: "remera",                en: "shirt",             icon: "shirt" },
  { id: "rop-bolsa",                 cat: "ropa",        es: "bolsa",                 en: "bag",               icon: "shopping-bag" },
  { id: "rop-cartera",               cat: "ropa",        es: "cartera",               en: "handbag",           icon: "handbag" },
  { id: "rop-reloj-pulsera",         cat: "ropa",        es: "reloj pulsera",         en: "watch",             icon: "watch" },
  { id: "rop-mochila",               cat: "ropa",        es: "mochila",               en: "backpack",          icon: "backpack" },
  { id: "rop-maletin",               cat: "ropa",        es: "maletín",               en: "briefcase",         icon: "briefcase" },
  { id: "rop-corona",                cat: "ropa",        es: "corona",                en: "crown",             icon: "crown" },
  { id: "rop-joya",                  cat: "ropa",        es: "joya",                  en: "gem",               icon: "gem" },
  { id: "rop-casco",                 cat: "ropa",        es: "casco",                 en: "hard hat",          icon: "hard-hat" },
  { id: "rop-gorro-de-graduacion",   cat: "ropa",        es: "gorro de graduación",   en: "graduation cap",    icon: "graduation-cap" },
  { id: "rop-zapatilla",             cat: "ropa",        es: "zapatilla",             en: "sport shoe",        icon: "sport-shoe" },
  { id: "rop-antifaz",               cat: "ropa",        es: "antifaz",               en: "mask",              icon: "venetian-mask" },
  { id: "rop-billetera",             cat: "ropa",        es: "billetera",             en: "wallet",            icon: "wallet" },
  { id: "rop-sombrero",              cat: "ropa",        es: "sombrero",              en: "hat",               icon: "hat-glasses" },
  // ── juguetes ──
  { id: "jug-pelota",                cat: "juguetes",    es: "pelota",                en: "ball",              icon: "volleyball" },
  { id: "jug-globo",                 cat: "juguetes",    es: "globo",                 en: "balloon",           icon: "balloon" },
  { id: "jug-bloque",                cat: "juguetes",    es: "bloque",                en: "toy brick",         icon: "toy-brick" },
  { id: "jug-rompecabezas",          cat: "juguetes",    es: "rompecabezas",          en: "puzzle",            icon: "puzzle" },
  { id: "jug-dado",                  cat: "juguetes",    es: "dado",                  en: "dice",              icon: "dice-5" },
  { id: "jug-joystick",              cat: "juguetes",    es: "joystick",              en: "joystick",          icon: "joystick" },
  { id: "jug-consola",               cat: "juguetes",    es: "consola",               en: "gamepad",           icon: "gamepad-2" },
  { id: "jug-tambor",                cat: "juguetes",    es: "tambor",                en: "drum",              icon: "drum" },
  { id: "jug-guitarra",              cat: "juguetes",    es: "guitarra",              en: "guitar",            icon: "guitar" },
  { id: "jug-piano",                 cat: "juguetes",    es: "piano",                 en: "piano",             icon: "piano" },
  { id: "jug-musica",                cat: "juguetes",    es: "música",                en: "music",             icon: "music" },
  { id: "jug-campana",               cat: "juguetes",    es: "campana",               en: "bell",              icon: "bell" },
  { id: "jug-camara",                cat: "juguetes",    es: "cámara",                en: "camera",            icon: "camera" },
  { id: "jug-computadora",           cat: "juguetes",    es: "computadora",           en: "computer",          icon: "computer" },
  { id: "jug-rueda-de-la-fortuna",   cat: "juguetes",    es: "rueda de la fortuna",   en: "ferris wheel",      icon: "ferris-wheel" },
  { id: "jug-trofeo",                cat: "juguetes",    es: "trofeo",                en: "trophy",            icon: "trophy" },
  { id: "jug-medalla",               cat: "juguetes",    es: "medalla",               en: "medal",             icon: "medal" },
  { id: "jug-bandera",               cat: "juguetes",    es: "bandera",               en: "flag",              icon: "flag" },
  { id: "jug-espada",                cat: "juguetes",    es: "espada",                en: "sword",             icon: "swords" },
  { id: "jug-varita",                cat: "juguetes",    es: "varita",                en: "wand",              icon: "wand" },
  { id: "jug-auriculares",           cat: "juguetes",    es: "auriculares",           en: "headphones",        icon: "headphones" },
  { id: "jug-microfono",             cat: "juguetes",    es: "micrófono",             en: "microphone",        icon: "mic" },
  { id: "jug-radio",                 cat: "juguetes",    es: "radio",                 en: "radio",             icon: "radio" },
  { id: "jug-regalo",                cat: "juguetes",    es: "regalo",                en: "gift",              icon: "gift" },
  { id: "jug-robot",                 cat: "juguetes",    es: "robot",                 en: "robot",             icon: "bot" },
  { id: "jug-caja-de-juguetes",      cat: "juguetes",    es: "caja de juguetes",      en: "toy box",           icon: "blocks" },
  { id: "jug-castillo",              cat: "juguetes",    es: "castillo",              en: "castle",            icon: "castle" },
  { id: "jug-burbujas",              cat: "juguetes",    es: "burbujas",              en: "bubbles",           icon: "bubbles" },
  { id: "jug-silbato",               cat: "juguetes",    es: "silbato",               en: "whistle",           icon: "whistle" },
  { id: "jug-escudo",                cat: "juguetes",    es: "escudo",                en: "shield",            icon: "shield" },
  // ── casa ──
  { id: "cas-iman",                  cat: "casa",        es: "imán",                  en: "magnet",            icon: "magnet" },
  { id: "cas-canasta",               cat: "casa",        es: "canasta",               en: "basket",            icon: "shopping-basket" },
  { id: "cas-carrito",               cat: "casa",        es: "carrito",               en: "shopping cart",     icon: "shopping-cart" },
  { id: "cas-entrada",               cat: "casa",        es: "entrada",               en: "ticket",            icon: "ticket" },
  // ── naturaleza ──
  { id: "nat-pala",                  cat: "naturaleza",  es: "pala",                  en: "spade",             icon: "spade" },
  // ── comida ──
  { id: "com-botella",               cat: "comida",      es: "botella",               en: "bottle",            icon: "bottle-wine" },
];

export const CARD_CATEGORIES: CardCategory[] = Array.from(new Set(CARDS.map((c) => c.cat))) as CardCategory[];

export function cardById(id: string): Card | undefined {
  return CARDS.find((c) => c.id === id);
}
